Update to BaseApp 23.06 and add data checker
flathub/org.sugarlabs.Chart pull request #4
Opened 2023-06-24 12:03 UTC by sparshg

Seems like upstream has an icon of 62x60 which is not square resulting in build error

2023-07-03 14:17 UTC, tchx84 commented
@sparshg yes, please fix whatever it's required.

2023-07-05 18:06 UTC, tchx84 requested changes
If I add a few values and try to graph it I get this

```
Traceback (most recent call last):
  File "/app/share/sugar/activities/Chart.activity/activity.py", line 704, in _add_chart_cb
    self.update_chart()
  File "/app/share/sugar/activities/Chart.activity/activity.py", line 826, in update_chart
    self._render_chart()
  File "/app/share/sugar/activities/Chart.activity/activity.py", line 766, in _render_chart
    self.current_chart.render()
  File "/app/share/sugar/activities/Chart.activity/chart.py", line 160, in render
    chart.render()
  File "/app/share/sugar/activities/Chart.activity/sugarpycha/chart.py", line 119, in render
    self._renderAxis(cx)
  File "/app/share/sugar/activities/Chart.activity/sugarpycha/chart.py", line 506, in _renderAxis
    self._renderYTick(cx, tick)
  File "/app/share/sugar/activities/Chart.activity/sugarpycha/chart.py", line 415, in _renderYTick
    return self._renderTick(cx, tick,
  File "/app/share/sugar/activities/Chart.activity/sugarpycha/chart.py", line 363, in _renderTick
    if isinstance(tick, collections.Callable):
AttributeError: module 'collections' has no attribute 'Callable'
```
It's also not preserving the values I add, most likely due to the bug above.

@sparshg , like we talked the other week, please test things carefully

2023-07-05 19:18 UTC, sparshg commented
Sorry, fixed the issue, working as expected now.

2023-07-05 20:50 UTC, tchx84 requested changes

2023-07-05 20:50 UTC, tchx84 commented on chart-port.patch
> ++        if isinstance(tick, collections.abc.Callable):
I grep'd the code, if this is the fix, we should probably fix it everywhere else.

```
grep "collections.Callable" -r .
./chart/sugarpycha/bar.py:                if isinstance(self.options.yvals.renderer, collections.Callable):
./chart/sugarpycha/chart.py:        if isinstance(tick, collections.Callable):
./chart/sugarpycha/polygonal.py:        if isinstance(tick, collections.Callable):
./chart/sugarpycha/polygonal.py:        if isinstance(tick, collections.Callable):
./chart/sugarpycha/radial.py:        if isinstance(tick, collections.Callable):
./chart/sugarpycha/radial.py:        if isinstance(tick, collections.Callable):

```

2023-07-10 21:04 UTC, tchx84 approved these changes

2023-07-10 21:04 UTC, merged